title: Minsuk Sung
url: "https://github.com/mssung94"
baseurl: ""

markdown: kramdown
ins_logo: "./korea-logo.png"

tracking_id: UA-138665784-2 #


footer: no
footer_url: "https://github.com/mssung94"
footer_text: "Minsuk Sung"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: ""
 - name: "CV"
   link: ""
 - name: "Blog"
   link: "https://minsuksung-ai.tistory.com/"
 - name: "Facebook"
   link: "https://www.facebook.com/minsuk.stone.sung/"

remote_theme: ankitsultana/researcher@gem

theme: jekyll-theme-cayman
