title: Heeseung Cho
url: "https://github.com/Heeseung-Cho"
baseurl: ""

markdown: kramdown
ins_logo: "./korea_logo.jpg"

tracking_id: UA-138665784-2 #


footer: no
footer_url: "https://github.com/Heeseung-Cho"
footer_text: "Heeseung Cho"

sass:
    style: compressed
    sass_dir: _sass

remote_theme: ankitsultana/researcher@gem

theme: jekyll-theme-cayman
